/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"
#include "token.h"
#include <fstream>

char **
request_authorization_1_svc(authorization_payload arg1, struct svc_req *rqstp)
{
	std::ofstream output_file;
	output_file.open("tests_output/test1/server.out", std::ios_base::app);
	output_file << "BEGIN " << arg1.id << " AUTHZ\n";

	static char *result = new char[16];

	strcpy(result, generate_access_token(arg1.id));

	output_file << "\tRequestToken = " << result << "\n";
	output_file.close();

	return &result;
}

access_token_response *
request_access_token_1_svc(authorization_payload arg1, access_token_payload arg2, struct svc_req *rqstp)
{
	static access_token_response result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *validate_delegated_action_1_svc(delegated_action_payload arg1, struct svc_req *rqstp)
{
	return NULL;
}
