/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"

bool_t
xdr_authorization_payload (XDR *xdrs, authorization_payload *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->refresh_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_token_payload (XDR *xdrs, access_token_payload *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_token_response (XDR *xdrs, access_token_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->resource_token, 16))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valability))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_delegated_action_payload (XDR *xdrs, delegated_action_payload *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->action, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_1_argument (XDR *xdrs, request_access_token_1_argument *objp)
{
	 if (!xdr_authorization_payload (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_access_token_payload (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
