/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"

void oauth_prog_1(char *host)
{
	CLIENT *clnt;
	char **result_1;
	authorization_payload request_authorization_1_arg1;
	access_token_response *result_2;
	authorization_payload request_access_token_1_arg1;
	access_token_payload request_access_token_1_arg2;

#ifndef DEBUG
	clnt = clnt_create(host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
}

int main(int argc, char *argv[])
{
	char *host;

	FILE* operations_file = fopen(argv[2], "r");

	

	host = argv[1];
	oauth_prog_1(host);
	exit(0);
}
