/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void (*)(int)
#endif

static char **
_request_authorization_1(authorization_payload *argp, struct svc_req *rqstp)
{
	return (request_authorization_1_svc(*argp, rqstp));
}

static access_token_response *
_request_access_token_1(request_access_token_1_argument *argp, struct svc_req *rqstp)
{
	return (request_access_token_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void
oauth_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		authorization_payload request_authorization_1_arg;
		request_access_token_1_argument request_access_token_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case REQUEST_AUTHORIZATION:
		_xdr_argument = (xdrproc_t)xdr_authorization_payload;
		_xdr_result = (xdrproc_t)xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *))_request_authorization_1;
		break;

	case REQUEST_ACCESS_TOKEN:
		_xdr_argument = (xdrproc_t)xdr_request_access_token_1_argument;
		_xdr_result = (xdrproc_t)xdr_access_token_response;
		local = (char *(*)(char *, struct svc_req *))_request_access_token_1;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

int main(int argc, char **argv)
{
	register SVCXPRT *transp;

	FILE *users_file = fopen(argv[1], "r");
	FILE *resources_file = fopen(argv[2], "r");
	FILE *approvals_file = fopen(argv[3], "r");

	int token_valability = atoi(argv[4]);

	typedef struct
	{
		char *user;
		char **resources;
		char **rights;
		int num_accesable_resources;
	} UserDetails;

	int num_users;
	int num_resources;
	fscanf(users_file, "%d", &num_users);
	fscanf(resources_file, "%d", &num_resources);

	char **resources = malloc(num_resources * sizeof(char *));
	for (int i = 0; i < num_resources; i++)
	{
		resources[i] = malloc(16 * sizeof(char));
		fscanf(resources_file, "%s", resources[i]);
	}

	UserDetails **user_details = malloc(num_users * sizeof(UserDetails *));

	for (int i = 0; i < num_users; i++)
	{
		UserDetails *current = malloc(sizeof(UserDetails));
		current->user = malloc(16 * sizeof(char));
		fscanf(users_file, "%s", current->user);

		current->num_accesable_resources = 0;
		char *current_line = malloc(100 * sizeof(char));
		fscanf(approvals_file, "%s", current_line);

		if (strcmp(current_line, "*,-") == 0)
		{
			current->resources = NULL;
			current->rights = NULL;
		}
		else
		{
			current->resources = malloc(num_resources * sizeof(char *));
			current->rights = malloc(num_resources * sizeof(char *));

			char *p = strtok(current_line, ",");
			int index = 0;

			while (p)
			{
				current->resources[index] = malloc((strlen(p) + 1) * sizeof(char));
				strcpy(current->resources[index], p);

				p = strtok(NULL, ",");
				current->rights[index] = malloc((strlen(p) + 1) * sizeof(char));
				strcpy(current->rights[index], p);

				p = strtok(NULL, ",");
				index++;
				current->num_accesable_resources++;
			}
		}

		user_details[i] = current;
	}

	pmap_unset(OAUTH_PROG, OAUTH_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL)
	{
		fprintf(stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, OAUTH_PROG, OAUTH_VERS, oauth_prog_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (OAUTH_PROG, OAUTH_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL)
	{
		fprintf(stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OAUTH_PROG, OAUTH_VERS, oauth_prog_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (OAUTH_PROG, OAUTH_VERS, tcp).");
		exit(1);
	}

	svc_run();

	fprintf(stderr, "%s", "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
