/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"

char **
request_authorization_1_svc(authorization_payload arg1,  struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

access_token_response *
request_access_token_1_svc(authorization_payload arg1, access_token_payload arg2,  struct svc_req *rqstp)
{
	static access_token_response  result;

	/*
	 * insert server code here
	 */

	return &result;
}
