/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"

bool_t
xdr_authorization_payload (XDR *xdrs, authorization_payload *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->refresh_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_authorization_response (XDR *xdrs, authorization_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, 16))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_authz_token_payload (XDR *xdrs, authz_token_payload *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_access_token_response (XDR *xdrs, access_token_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->resource_token, 16))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, 16))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valability))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_delegated_action_payload (XDR *xdrs, delegated_action_payload *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->action, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_action_response (XDR *xdrs, validate_action_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->action_output, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_req_token_response (XDR *xdrs, approve_req_token_response *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->auth_token, 16))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->is_signed))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_refresh_token_payload (XDR *xdrs, refresh_token_payload *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->refresh_token, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token_1_argument (XDR *xdrs, request_access_token_1_argument *objp)
{
	 if (!xdr_authorization_payload (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_authz_token_payload (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
